---

- name: Generate Variables
  hosts: all
  connection: local
  gather_facts: no

  roles:
   - zeroise-config

  tasks:

# Please enable SSH on MX before to execute the following tasks
  - name: Please wait...
    junos_config:
     provider: "{{ credentials }}"
     src: host_vars/{{ inventory_hostname }}/zeroise.conf
     update: override
