---

- name: Generate Variables
  hosts: all
  connection: local
  gather_facts: no

  roles:
   - zeroise-config

  tasks:

# Creating host_vars directories for each host
  - name: Create a Host vars directory for each node
    file: path=host_vars/{{ inventory_hostname }} state=directory

# Please enable SSH on MX before to execute the following tasks
  - name: Please wait...
    junos_config:
     provider: "{{ credentials }}"
     src: host_vars/{{ inventory_hostname }}/zeroise.conf
     update: override
